// 添加所需的图标
import {
    UserOutline,
    LoginOutline,
    AppstoreOutline,
    MenuFoldOutline,
    MenuUnfoldOutline,
    BellOutline,
    DeleteOutline,
    PlusOutline,
    PictureTwoTone,
    QuestionCircleOutline,
    NotificationOutline,
    MenuOutline,
    ShopOutline,
    TableOutline,
    PoundOutline,
    TrademarkOutline,
    SettingOutline,
    ProjectOutline,
    ShoppingOutline,
    LockOutline,
    MailOutline
} from "@ant-design/icons-angular/icons";

export const ICONS = [
    UserOutline,
    LoginOutline,
    AppstoreOutline,
    MenuFoldOutline,
    MenuUnfoldOutline,
    BellOutline,
    DeleteOutline,
    PlusOutline,
    PictureTwoTone,
    QuestionCircleOutline,
    NotificationOutline,
    MenuOutline,
    ShopOutline,
    TableOutline,
    PoundOutline,
    TrademarkOutline,
    SettingOutline,
    ProjectOutline,
    ShoppingOutline,
    LockOutline,
    MailOutline
]